import { createHash, randomUUID } from 'crypto';
import { mkdir, writeFile } from 'fs/promises';
import { isAbsolute, join, resolve } from 'path';
import { Injectable } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';

export interface StoredObject {
  key: string;
  checksumSha256: string;
  byteSize: number;
}

@Injectable()
export class PrivateObjectStorage {
  constructor(private readonly config: ConfigService) {}

  async putImage(buffer: Buffer, extension: string): Promise<StoredObject> {
    const checksumSha256 = createHash('sha256').update(buffer).digest('hex');
    // Keep object keys unique even when two logo variants (or a retry) happen
    // to produce identical bytes. The checksum remains content-addressable
    // metadata while the UUID prevents the database object-key constraint
    // from rejecting a legitimate second choice.
    const key = `generated/${new Date().toISOString().slice(0, 10)}/${randomUUID()}-${checksumSha256}.${extension}`;
    // The local adapter is the canonical development object store. Persist
    // generated bytes even when S3_ENDPOINT points at the compose MinIO URL;
    // the API and worker read the same local fallback path in this project.
    const endpoint = this.config.get<string>('S3_ENDPOINT') ?? 'file://./.local-object-storage';
    const configuredPath = endpoint.startsWith('file://') ? endpoint.replace('file://', '') || '../../.local-object-storage' : '../../.local-object-storage';
    const basePath = isAbsolute(configuredPath) ? configuredPath : resolve(process.cwd(), configuredPath);
    const fullPath = join(basePath, key);
    const separator = fullPath.lastIndexOf('\\') === -1 ? fullPath.lastIndexOf('/') : fullPath.lastIndexOf('\\');
    await mkdir(fullPath.slice(0, separator), { recursive: true });
    await writeFile(fullPath, buffer);

    return { key, checksumSha256, byteSize: buffer.byteLength };
  }
}
